#!/bin/sh
echo "                 _           _"
echo "                | |         | |"
echo " _ __   ___   __| | ___  ___| |_ ___ _ __"
echo "| '_ \ / _ \ / _' |/ _ \/ __| __/ _ \ '__|"
echo "| | | | (_) | (_| |  __/\__ \ ||  __/ |"
echo "|_| |_|\___/ \__,_|\___||___/\__\___|_|"
echo ""
echo "Installation in progress. DO NOT EXIT AT ANY TIME!"

if [ "$(id -u)" != "0" ]; then
	echo "Please run as root."
	exit 1
fi

rm -rf ./setup/tmp/
mkdir ./setup/tmp/
cd ./setup
./sys
./node
./redis
./vserver
cd ../
npm install
rm -rf ./setup/tmp/
